package models.world;

public enum WorldEvents {
	VOLCANIC_ERUPTION,
	MASSIVE_THUNDERSTORM,
	MASSIVE_BIRD_MIGRATION,
	MASSIVE_EARTHQUAKE,
	
	SOLAR_ECLIPSE,
	SCORCHING_SUN,
	
	BLOOD_MOON,
	MASSIVE_BATS_INVASION,
	ALIEN_INVASION,
	BLACKOUT;
}
